name: test
on: [push]
jobs:
  macos:
    name: test on macos
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install ghc
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh

      - name: test
        run: |
          cabal v2-test

  windows:
    name: test on windows
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install ghc
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install haskell-dev

      - name: refreshenv
        run: |
          refreshenv

      - name: test
        run: |
          cabal v2-test
